apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: img-grafana:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: grafana
        livenessProbe:
          httpGet:
            path: ./
            port: 3000
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: ./
            port: 3000
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 5
 

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  type: LoadBalancer
  ports:
    - port: 3000
      name: grafana





