apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-deploy
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: img-pma:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: phpmyadmin
        livenessProbe:
          httpGet:
            path : 
            port: 5000
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path : 
            port: 5000
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 5
 

---
apiVersion: v1
kind: Service
metadata:
  name: pma-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  ports:
    - port: 5000
      name: phpmyadmin





