CREATE DATABASE wordpress_db;

CREATE USER 'root'@'%' IDENTIFIED BY PASSWORD '';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';

CREATE USER 'admin'@'%' IDENTIFIED BY PASSWORD '*4ACFE3202A5FF5CF467898FC58AAB1D615029441';
GRANT SELECT, INSERT, UPDATE, DELETE ON *.* TO 'admin'@'%';

FLUSH PRIVILEGES;